<?php

namespace reketaka\helps\common\commands;

use common\helpers\BaseHelper;
use reketaka\helps\common\models\Regedit;
use yii\console\Controller;
use yii\helpers\Console;

class RegeditController extends Controller{

    /**
     * @var $regedit Regedit
     */
    public $regedit;

    public function init()
    {
        $this->regedit = \Yii::$app->regedit;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Возвращает значение переменной регистра
     * @param $path
     */
    public function actionGet($path){
        $var = $this->regedit->get($path);


        echo Console::ansiFormat($path, [Console::FG_YELLOW])." = ".$var.PHP_EOL;
        return;
    }

    /**
     * Возвращает список значений регистра
     * @param $path
     */
    public function actionGetList($path){
        $list = $this->regedit->getList($path);

        echo "List Variables:".PHP_EOL;

        $maxLength = 0;
        foreach($list as $d){
            $mx = strlen($d[0]);
            if($mx >= $maxLength){
                $maxLength = $mx;
            }
        }

        foreach($list as $d){
            list($name, $var) = $d;

            if(strlen($name) < $maxLength){
                for($a = 0;($maxLength - strlen($name));$a++){
                    $name .= ' ';
                }
            }

            echo Console::ansiFormat($name, [Console::FG_YELLOW]).' = '.Console::ansiFormat($var, [Console::FG_GREEN]).PHP_EOL;
        }
    }

    public function actionSet($path, $var){

        $this->regedit->set($path, $var);

        echo Console::ansiFormat("Variable set success", [Console::FG_YELLOW]).PHP_EOL;
        return true;

    }

    public function actionRemove($path){

        if($this->regedit->remove($path)){
            echo "Variable remove success".PHP_EOL;
            return true;
        }

        echo Console::ansiFormat("Cant remove variable", [Console::FG_YELLOW]).PHP_EOL;
        return true;
    }

}