<?php

namespace reketaka\helps\common\assets;

use reketaka\helps\common\helpers\Bh;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\AssetBundle;
use yii\web\View;

/**
 * Main backend application asset bundle.
 */
class BootstrapNotificationAsset extends AssetBundle
{
    public $sourcePath = '@npm/bootstrap-notify';
    public $js = [
        'bootstrap-notify.min.js'
    ];
    public $depends = [
        'yii\web\JqueryAsset',
    ];

    public function registerAssetFiles($view){
        parent::registerAssetFiles($view);

        $bsVersion = ArrayHelper::getValue(Yii::$app->params, 'bsVersion', 3);
        $bsVersion = Bh::onlyNumbers($bsVersion);
        if($bsVersion >= 4){
            $jsText = <<<JS
            var flashMessage = function(title, type = 'success', obj = {}){
                var _obj = {title:title, type:type, delay:15000};
                
                _obj = Object.assign(_obj, obj)
                $.toast(_obj);
            }
JS;
            $view->registerJs($jsText, View::POS_HEAD);

        }


    }

    public function init()
    {
        $bsVersion = ArrayHelper::getValue(Yii::$app->params, 'bsVersion', 3);
        $bsVersion = Bh::onlyNumbers($bsVersion);
        if($bsVersion >= 4){
            $this->sourcePath = '@npm/bs4-toast/src';
            $this->css = ['css/toast.css'];
            $this->js = ['js/toast.js'];
            $this->depends[] = 'yii\bootstrap4\BootstrapAsset';


        }




        parent::init(); // TODO: Change the autogenerated stub
    }
}
