<?php

namespace reketaka\helps\modules\basket\assets\basket;

use yii\web\AssetBundle;

class BasketAsset extends AssetBundle
{
    public $sourcePath = '@reketaka/helps/modules/basket/assets/basket/data';
    public $css = [
        'css/index.css'
    ];
    public $js = [
//        'js/azia.js'
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];
    
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}