<?php

namespace reketaka\helps\modules\basket\assets\basket;

use yii\web\AssetBundle;

class BasketAsset extends AssetBundle
{
    public $sourcePath = '@reketaka/helps/modules/basket/assets/basket/data';
    public $css = [
        'css/index.css'
    ];
    public $js = [
        'js/basket.js'
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'reketaka\helps\common\assets\BootstrapNotificationAsset'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}